# Generated by Django 4.1.2 on 2022-11-01 12:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("None", "Undefined")], default="None", max_length=100
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[("None", "Undefined")], default="None", max_length=100
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                (
                    "place",
                    models.CharField(
                        choices=[("None", "Undefined")], default="None", max_length=100
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=8)),
                ("additional_data", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
