# Generated by Django 4.1.2 on 2022-11-01 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("None", "Undefined")], default="None", max_length=100
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        choices=[("None", "Undefined")], default="None", max_length=100
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                (
                    "place",
                    models.CharField(
                        choices=[("None", "Undefined")], default="None", max_length=100
                    ),
                ),
                ("number", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=8)),
                ("additional_data", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
