# Generated by Django 4.1.2 on 2022-11-01 19:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extra_datas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("genders", "0001_initial"),
        ("borroweds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                (
                    "transaction",
                    models.CharField(
                        choices=[("Sale", "Sale"), ("Location", "Location")],
                        default="Location",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("available", models.BooleanField(default=True)),
                ("author", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=4)),
                (
                    "language",
                    models.CharField(
                        choices=[("Portuguese", "Portuguese"), ("English", "English")],
                        default="English",
                        max_length=10,
                    ),
                ),
                ("edition", models.CharField(max_length=254)),
                (
                    "condition",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("isbn", models.CharField(max_length=13)),
                (
                    "borrowed",
                    models.ManyToManyField(
                        related_name="books", to="borroweds.borrowed"
                    ),
                ),
                (
                    "extra_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="extra_datas.extra_data",
                    ),
                ),
                (
                    "genders",
                    models.ManyToManyField(related_name="books", to="genders.gender"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
