# Generated by Django 4.1.2 on 2022-11-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_genders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="edition",
            new_name="publishing",
        ),
    ]
