# Generated by Django 4.1.2 on 2022-11-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("extra_datas", "0001_initial"),
        ("books", "0005_book_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="extra_data",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="extra_datas.extra_data",
            ),
        ),
    ]
