# Generated by Django 4.1.2 on 2022-11-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gender",
            old_name="genders",
            new_name="gender",
        ),
    ]
