# Generated by Django 4.1.2 on 2022-11-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genders", "0002_rename_genders_gender_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gender",
            old_name="gender",
            new_name="genders",
        ),
    ]
