# Generated by Django 4.1.2 on 2022-11-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borroweds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowed",
            name="finish_date",
            field=models.DateField(null=True),
        ),
    ]
