# Generated by Django 4.1.2 on 2022-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borroweds", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowed",
            name="price_tatal_days",
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
