# Generated by Django 4.1.2 on 2022-11-06 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed_back", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rating_owner",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating_renter",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="stars_owner",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="stars_renter",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
